name: SCOS-BP
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch=2.5
  - pytorch-cuda=12.4
  - lightning=2.5
  - tensorboard=2.20
  - scipy=1.16
  - pandas=2.3
  - jupyter=1.1
  - matplotlib=3.10
  - ipywidgets=8.1
  - plotly=6.4
  - anywidget=0.9
  - voila=0.5
