name: scos-bp
channels:
  - conda-forge
  - defaults
dependencies:
  - osfclient
  - hydra-core=1.3
  - lightning=2.5
  - tensorboard
  - scipy
  - umap-learn
  - jupyter
  - streamlit
  - plotly
  - matplotlib
