data:
  # data
  data_load_fold: data/raw/
  y_as_y: false
  y_as_x: false
  # normalization
  mu: 115.0 # set to null if want per-measurement mu
  sd: 20.0  # set to null if want per-measurement sd
  # split
  # choices: MeasurementDependent, MeasurementIndependent, null
  split_type: MeasurementIndependent  
  split_ratio: [0.5, 0.2, 0.3]
  # filter
  # choices: X|Y, X, Y, X&Y, All, null
  filter_level: X
  # dataset
  channel_perm: false
  channel_drop: 0.0   # probability to enable channel drop
  channel_shift: 0
  # dataloader
  batch_size: 256
  num_workers: 0
