# @package _global_

defaults:
  - /schema/data@_here_
  - /schema/model@_here_
  - /schema/objective@_here_
  - _self_

ckpt_load_path: ???
data_save_fold: null
max_epochs: 1000

data:
  y_as_y: true
  filter_level: X&Y

objective:
  # model
  freeze_embedding: true
  freeze_transformer: -1
  freeze_head: true
  # stepRegressionAdapter, stepAdapter
  K: 50
  weight_shape: 1e-4
  weight_min: 0.5
  weight_max: 0.5
  # optimizer
  lr: 0.05
  step_size: 100
  gamma: 0.08
