# @package _global_

defaults:
  - /schema/data@_here_
  - /schema/model@_here_
  - /schema/objective@_here_
  - /schema/trainer@_here_
  - _self_

name: finetune

data:
  filter_level: X&Y

objective:
  # model
  freeze_embedding: true
  freeze_transformer: 4
  freeze_head: true
  # step
  task:
    stepRegressionAdapter: 1.0
  # stepRegressionAdapter
  K: 50
  weight_shape: 1e-4
  weight_min: 0.5
  weight_max: 0.5
  # optimizer
  lr: 0.1
  step_size: 100
  gamma: 0.1

trainer:
  max_epochs: 1000
  ckpt_load_path: ckpt/pretrain-h/last.ckpt
